version: 0.2

phases:
   install:
      runtime-versions:
         - nodejs: 12
         
         
   build:
      commands:
         - echo $CODEBUILD_INITIATOR
         - echo $CODEBUILD_SOURCE_REPO_URL
         - echo $CODEBUILD_SRC_DIR
         - ls
         - echo $CODEBUILD_SRC_DIR_source2
         - ls
         
artifacts:
   files:
      - file1